### PR TITLE
Fixes #15, by adding api call

### LINKED ISSUE #15: Toggle on index screen
Hi! It's a great feature but I have a doubt, I try to add a toggle field in the index but only display a dot with red or green color, I'm not sure if I am missing something or why It's not working, can somebody explain me? Thanks

### PR DESCRIPTION
**Pull request by bernhardh**
I have created a documentation for it as well. 

Not sure if this is the best way to do it, but you need to add the current resource id to the method:

```php
Toggle::make('Active')->editableIndex($this->resource->id)
```

because in the vue component, we do not get the current id (or maybe I have overseen anything).

### CODE REVIEW

**Comment by davidpiesse** [comment]
Looks OK.
Would this be a way to get the resourceId without passing it in?
https://github.com/pdmfc/nova-inline-text/blob/master/resources/js/components/IndexField.vue#L62-L64

They also seem to not have a specific API controller but use the underlying Resource API to update a field.

**Comment by bernhardh** [comment]
Thanks for checking.

# Getting the id

Getting the id by `this.$parent.resource.id.value` was my first thought, but then I have done it as I did, because I thought its not the best practice to access parent data which you can't control. 

But you are right! I have changed it know, because the benefit of it is too big (no need to add it in the make command).

What I really don't like is this part in the link you mentioned:

```
this.$parent.$parent.$parent.$parent.$parent.$parent.getResources();
```
Thats like opening the box of pandora in my eyes.

# Using the build in api

Thats as well an option I first thought about. But it isn't working with validation, since you don't have access to all fields. See https://github.com/pdmfc/nova-inline-text/issues/8 which is a deal breaker in my eyes. Thats why I decided to use my own controller.

Your thoughts?

**Comment by davidpiesse** [comment]
Awesome - pushing into 0.0.8 pre-release.
Let me know how it goes.

**Comment by bernhardh** [comment]
Thanks for merging!

**Comment by skoyah** [comment]
Hi there!

Thanks for pointing this out on my nova-inline package.
I totally agree with your point of view.  It feels weird to make all these hacks just to update a single field on the resource.

I was thinking also on creating a custom endpoint to deal with the functionality but was kinda stuck with a lot of work in between.

Thanks for referencing the issue!

**Pull request merged**
